# File: k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: chinmayee
type: Opaque
data:
  # Replace these with your actual base64 values
  jwt-secret: TXlTZWNyZXQxIQ==
  cloud-name: ZGV2ZWxvcG1lbnQ=
  cloud-api-key: NzY5MzgzNzUyNjE5OTU0
  cloud-api-secret: UFBuZG1VVjdqOUx2UG5qTi1yNy01TUdBa1dj
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvZmxvcg==
